//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCalculator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts_ar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts_ar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartCalculator.Properties.Texts_ar", typeof(Texts_ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد؟.
        /// </summary>
        internal static string AreYouSure_ {
            get {
                return ResourceManager.GetString("AreYouSure?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثنائي.
        /// </summary>
        internal static string BIN {
            get {
                return ResourceManager.GetString("BIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ حسابي.
        /// </summary>
        internal static string CalculatingError {
            get {
                return ResourceManager.GetString("CalculatingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضع غير صالح للآلة الحاسبة
        ///أعد تشغيل الآلة الحاسبة.
        /// </summary>
        internal static string CalculatorModeError {
            get {
                return ResourceManager.GetString("CalculatorModeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مئوية.
        /// </summary>
        internal static string Celsius {
            get {
                return ResourceManager.GetString("Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في التحويل.
        /// </summary>
        internal static string ConversionError {
            get {
                return ResourceManager.GetString("ConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عشري.
        /// </summary>
        internal static string DEC {
            get {
                return ResourceManager.GetString("DEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فهرنهايت.
        /// </summary>
        internal static string Fahrenheit {
            get {
                return ResourceManager.GetString("Fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساعدة.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ست عشري.
        /// </summary>
        internal static string HEX {
            get {
                return ResourceManager.GetString("HEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلفن.
        /// </summary>
        internal static string Kelvin {
            get {
                return ResourceManager.GetString("Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استخدم هذه النافذة لتغيير لغة البرنامج.
        ///
        ///اللغات المتوفرة:
        ///• اللغة العربية
        ///• اللغة الإنجليزية.
        /// </summary>
        internal static string LanguageFormHelp {
            get {
                return ResourceManager.GetString("LanguageFormHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحاسبة الذكية.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثماني.
        /// </summary>
        internal static string OCT {
            get {
                return ResourceManager.GetString("OCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في قراءة ملف المتغيرات &apos;Variables.txt&apos;.
        /// </summary>
        internal static string ReadingVariablesError {
            get {
                return ResourceManager.GetString("ReadingVariablesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمكن أن تستخدم هذه المتغيرات في الآلة الحاسبة
        ///استخدم هذه النافذة للتعديل على قيم المتغيرات.
        /// </summary>
        internal static string VariablesHelp {
            get {
                return ResourceManager.GetString("VariablesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحذير.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
